---
# tasks file for deploy_apache_web
- name   : Check and print OS family
  debug  :
   var   : ansible_os_family

- name   : Check and print System
  debug  :
   var   : ansible_system

#если RedHat
#Установка веб-сервера и проверка на OS
- block  :

  - name : Install Apache web server for "RedHat"
    yum  : name=httpd state=latest

#Запуск веб-северва
  - name    : Start web server and make enable on boot for "RedHat"
    service : name=httpd state=restarted

  when      : ansible_os_family == "RedHat"

#если Debian (Ubuntu)
- block  :

#Установка веб-сервера и проверка на OS
  - name : Install Apache web server for "Debian"
    apt  : name=apache2 state=latest

#Запуск веб-северва
  - name    : Start web server and make enable on boot for "Debian"
    service : name=apache2 state=started enabled=yes

  when      : ansible_os_family == "Debian"

#Перенос файла сайта на сервер в папку веб-сервера
- name   : Copy index.html to servers
  copy   : src={{ item }} dest={{ destin_folder }} mode=0555
  loop:
    - "index.html"
  notify :
    - Restart Apache2 (RedHat)
    - Restart Apache2 (Debian)
