---
- name   : Lessons 17
  hosts  : all
  become : yes

  vars:
   myText: "Hello! Today is sunday-funday!"

  tasks:
  - name: Ping server
    ping:

  - name: Create folders
    include: create_folders.yml

  - name: Create files
    include: create_files.yml
